#!/usr/bin/env bash
set -e

echo "Running Ruff autofix & format..."
ruff check --fix .
ruff format .

# Re-stage any files modified by Ruff
git update-index --again

echo "Running Mypy..."
mypy --no-incremental .

if [ -n "$CONDA_DEFAULT_ENV" ]; then
    conda env export -n dorker --no-builds | grep -v "^prefix: " > environment.yml
    git add environment.yml
fi