CREATE TABLE IF NOT EXISTS applications (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    job_id TEXT NOT NULL,
    match_id UUID NOT NULL,

    summary TEXT,
    follow_up_message TEXT,
    cover_letter TEXT,

    materials JSONB NOT NULL,

    debug JSONB,
    version TEXT,
    iteration SMALLINT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,

    FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE,
    FOREIGN KEY (match_id) REFERENCES matches(id) ON DELETE CASCADE
);