name: dorker

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dorker_db
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  postgres-backup:
    image: prodrigestivill/postgres-backup-local:16-alpine
    container_name: postgres_backup
    restart: unless-stopped
    user: postgres:postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: dorker_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      SCHEDULE: "0 12 * * *" # Runs daily at 12:00 PM
      BACKUP_KEEP_DAYS: 7
      BACKUP_KEEP_WEEKS: 4
      BACKUP_KEEP_MONTHS: 6
      POSTGRES_EXTRA_OPTS: "-F c -b -v" # Custom compressed format
    volumes:
      - ./backups:/backups
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge