from typing import List, Protocol, Tuple
from uuid import UUID

from src.shared import SuitabilityTier
from src.shared.models import ApplicationGeneratedResponse, JobForAnalytics


class MatchingProvider(Protocol):
    async def get_matching_count(self) -> dict[str, int]: ...
    async def get_matched_job(
        self, tiers: List[SuitabilityTier], offset: int = 0
    ) -> JobForAnalytics | None: ...
    async def get_job_by_match_id(self, match_id: UUID) -> JobForAnalytics | None: ...
    async def update_pipeline_status(self, match_id: UUID, status: str) -> None: ...
    async def generate_application_for_match(
        self, job: JobForAnalytics
    ) -> ApplicationGeneratedResponse: ...


class Classifier[T](Protocol):
    async def classify(self, job: JobForAnalytics) -> T: ...


class SLM(Protocol):
    def load_model(self) -> None: ...
    def generate[O](self, inp: JobForAnalytics, schema: type[O]) -> O: ...


class ApplicationGenerator[T](Protocol):
    async def generate_sync(self, job: JobForAnalytics) -> T: ...
    async def queue_generation(self, jobs: List[JobForAnalytics]) -> None: ...
    async def harvest_results(self) -> List[Tuple[UUID, T]]: ...
